version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: src/taxipred/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: src/taxipred/frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env